// This file is part of the Genova project licensed under the GNU General Public License v3.0.
// See the LICENSE file in the project root for more information.

using Genova.Common.Attributes;

namespace Genova.Conduit.Models;

/// <summary>
/// Represents the role of a message in a chat-based interaction.
/// </summary>
[CodeQuality(Public = true, Justification = "Intended for use by libraries and applications.")]
public enum ChatMessageRole
{
    /// <summary>
    /// A system-level instruction that guides the assistant's behavior.
    /// </summary>
    System,

    /// <summary>
    /// A message originating from the end user.
    /// </summary>
    User,

    /// <summary>
    /// A message generated by the assistant.
    /// </summary>
    Assistant,

    /// <summary>
    /// A message produced by a tool invocation.
    /// </summary>
    Tool,
}
