// This file is part of the Genova project licensed under the GNU General Public License v3.0.
// See the LICENSE file in the project root for more information.

namespace Genova.Conduit.Models;

/// <summary>
/// Client abstraction for generating vector embeddings from text inputs.
/// </summary>
public interface IEmbeddingModelClient
{
    /// <summary>
    /// Generates embeddings for the specified <paramref name="request"/>.
    /// </summary>
    /// <param name="request">The embedding request to process.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>The embeddings generated by the model.</returns>
    Task<EmbeddingResult> GenerateEmbeddingsAsync(
        EmbeddingRequest request,
        CancellationToken cancellationToken = default);
}
